name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --no-build

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --command make
